version: "2.2"

services:
  postgres:
    image: cr.yandex/crp649c8570akro5vmp6/postgres:13.2-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: shop
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - data:/var/lib/postgresql/data
    networks:
      - app-network
    mem_limit: 3G
    ulimits:
      nofile:
        soft: 12000
        hard: 12000
    cpus: 1.75

  gateway:
    restart: always
    build:
      context: .
      dockerfile: ./docker/gateway/Dockerfile
    tty: true
    depends_on:
      - shop
    ports:
      - "4040:4040"
    networks:
      - app-network
    ulimits:
      nofile:
        soft: 12000
        hard: 12000

  shop:
    container_name: shop
    build: ./docker/back
    restart: always
    depends_on:
      - postgres
    environment:
      POSTGRES_PASSWORD: backendrole
      POSTGRES_USER: backendrole
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_DB: shop
    volumes:
      - data:/images
    networks:
      - app-network
    mem_limit: 4G
    ulimits:
      nofile:
        soft: 12000
        hard: 12000
    cpus: 2.25

networks:
  app-network:
    driver: bridge

volumes:
  data:

