- name: Removing service {{ service_name }}
  debug:
    msg: "Removing {{ service_name }}"

- name: Stop service {{ service_name }}
  systemd: name={{ service_name }} state=stopped

- name: Cleanup volumes
  command:
    cmd: docker-compose down --volumes --rmi local
    chdir: "/home/ctfcup/{{ service_name }}"
  ignore_errors: yes

- name: Cleanup directory
  file:
    state: absent
    path: "/home/ctfcup/{{ service_name }}"

