- name: systemd config
  template: src=cs.web.service.j2 dest=/etc/systemd/system/cs.web.service
  notify:
    - reload systemd
  tags: update

- name: apt keys
  apt_key: url=https://nginx.org/keys/nginx_signing.key

- name: nginx repo source
  apt_repository:
    repo: deb http://nginx.org/packages/{{ ansible_distribution|lower }}/ {{ ansible_distribution_release }} nginx
    filename: nginx
    validate_certs: no

- name: nginx
  apt: name=nginx state=latest update_cache=yes

- name: nginx cache catalog
  file:
    path: /var/cache/nginx/cs
    state: directory
    owner: nginx
    group: root
    mode: 0700

- name: nginx data catalog
  file:
    path: /var/www
    state: directory
    owner: nginx
    group: root
    mode: 0755

- name: nginx config
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
    owner: root
    group: root
    mode: 0644
  notify:
    - restart nginx
  tags: update

- name: nginx remove default.conf
  file:
    path: /etc/nginx/conf.d/default.conf
    state: absent
  notify:
    - restart nginx

- name: nginx cs config
  template:
    src: cs.nginx.conf.j2
    dest: /etc/nginx/conf.d/cs.conf
    owner: root
    group: root
    mode: 0644
  notify:
    - restart nginx
  tags: update

- name: deploy logos
  synchronize: src="../../../../teams/logos" dest="/var/www/"

