FROM golang:1.17.3-alpine3.15 as build

WORKDIR /app

ENV GO111MODULE=on
ENV CGO_ENABLED=0

COPY go.mod go.sum ./
RUN go mod download

COPY pkg pkg
COPY cmd/controlpanel cmd/controlpanel

RUN go build -o controlpanel ./cmd/controlpanel

FROM scratch

COPY --from=build /app/controlpanel .

ENTRYPOINT ["./controlpanel"]