version: "2.2"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile-web
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - CP_ADDR=controlpanel:9090
      - SESSIONS_KEY="TFMyyqx&AK;MCbmYnnA-DuMpe"
    volumes:
    - ./cmd/web/templates:/templates
    restart: always
    depends_on:
      - controlpanel
    mem_limit: 1G
    pids_limit: 10

  controlpanel:
    build:
      context: .
      dockerfile: Dockerfile-cp
    ports:
      - "9090:9090"
    environment:
      - PORT=9090
      - WEB_ADDR=web
    volumes:
      - ./data:/db
    restart: always
    mem_limit: 1G
    pids_limit: 10
