FROM golang:1.17.3-alpine3.15 as build

WORKDIR /app

ENV GO111MODULE=on
ENV CGO_ENABLED=0

COPY go.mod go.sum ./
RUN go mod download

COPY pkg pkg
COPY cmd/web cmd/web

RUN go build -o web ./cmd/web

FROM scratch

COPY --from=build /app/cmd/web/templates ./templates
COPY --from=build /app/web .

ENTRYPOINT ["./web"]