version: "2.2"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile-web
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - CP_ADDR=controlpanel:9090
    restart: always
    depends_on:
      - controlpanel
    mem_limit: 1G
    pids_limit: 10

  controlpanel:
    build:
      context: .
      dockerfile: Dockerfile-cp
    ports:
      - "9090:9090"
    environment:
      - PORT=9090
    #volumes:
    #  - data:/app/db
    restart: always
    mem_limit: 1G
    pids_limit: 10

#volumes:
#  data:
