
name: Check 5g_shop
on:
  push:
    branches:
      - main
    paths:
      - 'services/5g_shop/**'
      - 'checkers/5g_shop/**'
  workflow_dispatch:
    inputs:
      cleanup_before_deploy:
        description: 'Stops and fully removes service (with volumes!) before deploying again. Type "yes" to do it.'
        required: false
        default: "no"

jobs:
  check_5g_shop:
    name: Check 5g_shop
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Run prebuilt hook
      run: if [ -f services/5g_shop/before_image_build.sh ]; then (cd ./services/5g_shop && ./before_image_build.sh); fi

    - name: Setup 5g_shop
      run: (cd ./services/5g_shop && docker-compose pull && docker-compose build && docker-compose up --build -d)

    - name: Prepare python for checker
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Setup checker libraries
      run: if [ -f checkers/5g_shop/requirements.txt ]; then python -m pip install -r checkers/5g_shop/requirements.txt; fi

    - name: Test checker on service
      run: (cd ./checkers/5g_shop && ./checker.py TEST 127.0.0.1)

  update_5g_shop:
    name: Deploy service using ansible to first teams
    needs: check_5g_shop
    runs-on: deployer
    #if: ${{ false }} # disable on game just in case

    steps:
    #- name: install ansible
    #  run: sudo apt-get install -y ansible

    - name: Checkout repo
      uses: actions/checkout@v2

    - name: change permission for ssh key
      run: chmod 0600 ./teams/for_devs.ssh_key

    - name: Run prebuilt hook
      run: if [ -f services/5g_shop/before_image_build.sh ]; then (cd ./services/5g_shop && ./before_image_build.sh); fi

    - name: update checkers
      run: cd ./ansible && ansible-playbook cs-checkers.yml

    - name: deploy 5g_shop
      run: cd ./ansible && ansible-playbook --extra-vars cleanup_service=${{ github.event.inputs.cleanup_before_deploy }} -t 5g_shop -l 5g_shop deploy-services.yml

